name: Build e Push para Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Construir e Enviar Imagem Docker
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # 2) Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3) Construção (build) da imagem Docker
      - name: Build da Imagem
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/minha-pagina-web:latest .

      # 4) Publicação (push) da imagem no Docker Hub
      - name: Push para Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/minha-pagina-web:latest
